version: '3.8'

services:
  wordpress:
    build: .  
    container_name: ${CONTAINER_NAME}
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env  # Načítá hesla ze souboru .env
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "${HTTP_PORT}:80"
      - "${SSH_PORT}:22"
    networks:
      - default

  mysql:
    image: mariadb:10.6
    container_name: ${CONTAINER_DBNAME}
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env  # Načítá hesla ze souboru .env
    ports:
      - "${DB_PORT}:3306"
    networks:
      - default

networks:
  default:
    name: ${NETWORK_NAME}
    driver: bridge
