version: '3.8'

services:
  php:
    build: .
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./public:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./data:/${DIRECTORY}

    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    networks:
      - default
      
  maria:
    image: mariadb:latest
    container_name: befit_db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - default

networks:
  default:
    name: ${NETWORK_NAME}
    driver: bridge
